// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiudujpqenjoufjgtqbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdWR1anBxZW5qb3Vmamd0cWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDM4NTksImV4cCI6MjA5MDExOTg1OX0._lv2HhYDKq_bO5lOjY-m8RsZbRCrk7PE6vZlruYnomo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});